Repository Sunlitt/SunKit, pull requests merged in 2023-04, with the labels that each got.

#27 bugFix/ThePackageDoesNotWorkWellWithDaylightSavingTime.
  Sources/SunKit/Extensions.swift
  Sources/SunKit/Sun.swift
  Tests/SunKitTests/UT_Sun.swift
Labels: bug

#29 Added Blue Hour
  Sources/SunKit/Sun.swift
  Sources/SunKit/SunElevationEvents.swift
Labels: enhancement

#30 Update README.md
  .swiftpm/xcode/package.xcworkspace/xcuserdata/nmariniello.xcuserdatad/UserInterfaceState.xcuserstate
  README.md
  Sources/SunKit/Sun.swift
  Tests/SunKitTests/UT_Sun.swift
  Tests/SunKitTests/UT_SunUseSameTimeZone.swift
Labels: documentation

#32 Removed 'UseSameTimeZone' dependency
  Sources/SunKit/HMS.swift
  Sources/SunKit/Sun.swift
  Sources/SunKit/SunElevationEvents.swift
  Sources/SunKit/Utils.swift
  Tests/SunKitTests/UT_SunUseSameTimeZone.swift
  Tests/SunKitTests/UT_Utils.swift
Labels: enhancement

#34 morning blue hour fix
  Sources/SunKit/Sun.swift
Labels: bug

#36 Changed names
  README.md
  Sources/SunKit/Sun.swift
  Tests/SunKitTests/UT_Sun.swift
Labels: enhancement

#37 Fixed "down" typos
  .swiftpm/xcode/package.xcworkspace/xcuserdata/nmariniello.xcuserdatad/UserInterfaceState.xcuserstate
  README.md
  Sources/SunKit/Sun.swift
  Tests/SunKitTests/UT_Sun.swift
Labels: enhancement

#38 Night goes from sunset to sunrise
  .swiftpm/xcode/package.xcworkspace/xcuserdata/nmariniello.xcuserdatad/UserInterfaceState.xcuserstate
  Sources/SunKit/Sun.swift
Labels: bug
